In [12]:
import pandas as pd

In [13]:
#Lendo dados
dados = pd.read_csv('projeto_guaraves.csv')

In [14]:
dados.head()

,Local,Data do sistema,Horario do sistema,Data,Horario,Temperatura do exterior(°C),Sensor de temperatura 4(°C),Sensor 1 de humidade (%),Estado do tunel,Sensor de temperatura 1 (°C),Sensor de temperatura 5 (°C),Sensor 2 de humidade (%),Pedido da refrigeracao do tunel (%),Sensor de temperatura 2 (°C),Temperatura (°C),Sensor de pressao (Pa),Pedido de pressao estatica (Pa),Sensor de temperatura 3 (°C),Humidade (%),Velocidade do ar (m/s)
0,amaratuba,09/02/2022,16:24,01/10/2021,11:32,-99.8,25.0,77,NaN,28.2,27.1,88,100,28.1,10.0,53.4,40.0,27.6,85,2.9
1,amaratuba,09/02/2022,16:24,01/10/2021,11:32,-99.8,25.0,77,NaN,28.2,27.1,88,100,28.1,10.0,53.4,40.0,27.6,85,2.9
2,amaratuba,09/02/2022,16:24,01/10/2021,11:32,-99.8,25.0,77,NaN,28.2,27.1,88,100,28.1,10.0,53.4,40.0,27.6,85,2.9
3,amaratuba,09/02/2022,16:24,01/10/2021,11:32,-99.8,25.0,77,NaN,28.2,27.1,88,100,28.1,10.0,53.4,40.0,27.6,85,2.9
4,amaratuba,09/02/2022,16:24,01/10/2021,11:32,-99.8,25.0,77,NaN,28.2,27.1,88,100,28.1,10.0,53.4,40.0,27.6,85,2.9

In [15]:
dados

,Local,Data do sistema,Horario do sistema,Data,Horario,Temperatura do exterior(°C),Sensor de temperatura 4(°C),Sensor 1 de humidade (%),Estado do tunel,Sensor de temperatura 1 (°C),Sensor de temperatura 5 (°C),Sensor 2 de humidade (%),Pedido da refrigeracao do tunel (%),Sensor de temperatura 2 (°C),Temperatura (°C),Sensor de pressao (Pa),Pedido de pressao estatica (Pa),Sensor de temperatura 3 (°C),Humidade (%),Velocidade do ar (m/s)
0,amaratuba,09/02/2022,16:24,01/10/2021,11:32,-99.8,25.0,77,NaN,28.2,27.1,88,100,28.1,10.0,53.4,40.0,27.6,85,2.9
1,amaratuba,09/02/2022,16:24,01/10/2021,11:32,-99.8,25.0,77,NaN,28.2,27.1,88,100,28.1,10.0,53.4,40.0,27.6,85,2.9
2,amaratuba,09/02/2022,16:24,01/10/2021,11:32,-99.8,25.0,77,NaN,28.2,27.1,88,100,28.1,10.0,53.4,40.0,27.6,85,2.9
3,amaratuba,09/02/2022,16:24,01/10/2021,11:32,-99.8,25.0,77,NaN,28.2,27.1,88,100,28.1,10.0,53.4,40.0,27.6,85,2.9
4,amaratuba,09/02/2022,16:24,01/10/2021,11:32,-99.8,25.0,77,NaN,28.2,27.1,88,100,28.1,10.0,53.4,40.0,27.6,85,2.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100975,amaratuba,09/02/2022,16:24,01/10/2021,11:32,-99.8,25.0,77,NaN,28.2,27.1,88,100,28.1,10.0,53.4,40.0,27.6,85,2.9
100976,amaratuba,09/02/2022,16:24,01/10/2021,11:32,-99.8,25.0,77,NaN,28.2,27.1,88,100,28.1,10.0,53.4,40.0,27.6,85,2.9
100977,amaratuba,09/02/2022,16:24,01/10/2021,11:32,-99.8,25.0,77,NaN,28.2,27.1,88,100,28.1,10.0,53.4,40.0,27.6,85,2.9
100978,amaratuba,09/02/2022,16:24,01/10/2021,11:32,-99.8,25.0,77,NaN,28.2,27.1,88,100,28.1,10.0,53.4,40.0,27.6,85,2.9
100979,amaratuba,09/02/2022,16:24,01/10/2021,11:32,-99.8,25.0,77,NaN,28.2,27.1,88,100,28.1,10.0,53.4,40.0,27.6,85,2.9

In [ ]:
#Com 3 fotos por segundos, em 6 meses teremos 5.184.000